import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={`min-h-screen flex flex-col overflow-y-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex-1 w-full flex items-center justify-center overflow-hidden">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}